<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'core\\foo1' => $baseDir . '/core/foo1.php',
    'core\\foo2' => $baseDir . '/core/foo2.php',
    'core\\foo3' => $baseDir . '/core/foo3.php',
    'core\\foo4' => $baseDir . '/core/foo4.php',
    'core\\foo5' => $baseDir . '/core/foo5.php',
    'core\\foo6' => $baseDir . '/core/foo6.php',
);
