<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit815586e4d4979378807fb611fd3bad41
{
    public static $prefixLengthsPsr4 = array (
        'c' => 
        array (
            'core\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'core\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'core\\foo1' => __DIR__ . '/../..' . '/core/foo1.php',
        'core\\foo2' => __DIR__ . '/../..' . '/core/foo2.php',
        'core\\foo3' => __DIR__ . '/../..' . '/core/foo3.php',
        'core\\foo4' => __DIR__ . '/../..' . '/core/foo4.php',
        'core\\foo5' => __DIR__ . '/../..' . '/core/foo5.php',
        'core\\foo6' => __DIR__ . '/../..' . '/core/foo6.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit815586e4d4979378807fb611fd3bad41::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit815586e4d4979378807fb611fd3bad41::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit815586e4d4979378807fb611fd3bad41::$classMap;

        }, null, ClassLoader::class);
    }
}

